runtime: go
api_version: go1

handlers:

# Otherwise, find file in static directory
- url: /static
  static_dir: static

# All URLs are handled by the Go application script
- url: /.*
  script: _go_app

